name: Ci

on:
  push:
    branches:
      - main  # Change this to your repository's main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Choose your desired Python version

    - name: Install Ansible
      run: pip install ansible
      # Add the remote host's fingerprint to known_hosts
      - name: Add Host Key to known_hosts
        run: ssh-keyscan -H 178.128.232.4 >> ~/.ssh/known_hosts
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
    - name: Run Ansible playbook
      run: ansible-playbook -i  infra/ansible/servers.ini ./infra/ansible/pipeline.yml --extra-vars "local_directory=${{ github.workspace }}" 
